service: serverless-webpack-offline-example

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    google_cse_id: "004153151002543507975:hfhtuy-o10a"

custom:
  webpackIncludeModules: true

functions:
  header:
    handler: handler.header
    events:
      - http:
          path: header
          method: get
  normal:
    handler: handler.normal
    events:
      - http:
          path: normal
          method: get
          integration: lambda
  bongBot:
    handler: handler.bongBot
    events:
      - http:
          path: bongBot
          method: get
          integration: lambda
  promise:
    handler: handler.promise
    events:
      - http:
          path: promise
          method: get
          integration: lambda