service: serverless-webpack-offline-example

# Add the serverless-webpack plugin
# plugins:
  # - serverless-webpack
  # - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    google_cse_id: "XXX"
    google_cse_api_key: "XXXX"

# custom:
#   webpack:
#     webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
#     includeModules: true
#     packager: 'npm'   # Packager that will be used to package your external modules

functions:
  header:
    handler: src/handler.header
    events:
      - http:
          path: header
          method: get
          integration: lambda
  normal:
    handler: src/handler.normal
    events:
      - http:
          path: normal
          method: get
          integration: lambda
  bongBot:
    handler: src/handler.bongBot
    events:
      - http:
          path: bongBot
          method: get
          integration: lambda
  promise:
    handler: src/handler.promise
    events:
      - http:
          path: promise
          method: get
          integration: lambda